backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "galleries"
    label: "Galleries"
    files:
      - name: "content"
        label: "Site Galleries"
        file: "data/galleries.json"
        format: "json"
        fields:
          - { label: "Sports Photos", name: "sports_photos", widget: "list", field: { label: "Image", name: "image", widget: "image" } }
