backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "galleries"
    label: "Galleries"
    files:
      - name: "galleries"
        label: "All Galleries"
        file: "data/galleries.json"
        format: "json"
        fields:
          - { label: "Sports", name: "sports", widget: "object", fields:
              [
                { label: "Photos", name: "photos", widget: "list", field: { label: "Image", name: "image", widget: "image" } },
                { label: "Videos", name: "videos", widget: "list", field: { label: "Video", name: "video", widget: "file" } }
              ]
            }
